#!/usr/bin/env bash
# Render _data/ref.bibtex → GB/T 7714-2015 (numeric) HTML → _includes/publications.html
#
# Requires: pandoc ≥ 2.11 (with --citeproc). Pandoc 3.x has it built in.
#
# Usage:
#   bash bibtex_build/render.sh
#
# The generated file is committed to the repo so that GitHub Pages (which
# runs in --safe mode and cannot execute this script) gets a pre-rendered
# output. Re-run it whenever _data/ref.bibtex changes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIB="${REPO_ROOT}/_data/ref.bibtex"
CSL="${REPO_ROOT}/bibtex_build/china-national-standard-gb-t-7714-2015-numeric.csl"
OUT="${REPO_ROOT}/_includes/publications.html"

if ! command -v pandoc >/dev/null 2>&1; then
  echo "ERROR: pandoc not found on PATH." >&2
  echo "Install from https://pandoc.org/installing.html (Windows: download the msi)." >&2
  exit 1
fi
for f in "${BIB}" "${CSL}"; do
  if [[ ! -f "${f}" ]]; then
    echo "ERROR: ${f} not found." >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${OUT}")"

# Pipe a tiny Markdown stub with `nocite: '@*'` so pandoc emits the full
# bibliography as a <div id="refs" class="references csl-bib-body">…</div>
# fragment (no full <html> document wrapper).
BODY="$(pandoc \
  --citeproc \
  --bibliography="${BIB}" \
  --csl="${CSL}" \
  --from=markdown+citations \
  --to=html5 \
  --wrap=none \
  --quiet \
  <<'MD'
---
nocite: |
  @*
---
MD
)"

# Wrap with our own container so the page CSS can target `.publications`
# without conflicting with the global `csl-bib-body` / `references` rules.
# We leave pandoc's wrapper div as-is — nesting it inside ours is harmless.
#
# Two post-processing tweaks the CSL doesn't make easy to express as options:
#   1. The "GB/T 7714 numeric" CSL emits [J/OL] for journal articles with
#      a URL (the /OL is the "online" carrier flag). The user prefers plain
#      [J] on this site, so we strip the /OL suffix for the common types.
#   2. The same CSL uses zh-CN locale and emits "等" for 3+ authors. The user
#      wants English on both pages, so we substitute "et al.".
{
  echo '<!-- This file is auto-generated by bibtex_build/render.sh. Do not edit by hand. -->'
  echo '<div class="publications">'
  printf '%s\n' "${BODY}" \
    | sed -E \
        -e 's|\[J/OL\]|[J]|g' \
        -e 's|\[M/OL\]|[M]|g' \
        -e 's|\[D/OL\]|[D]|g' \
        -e 's|\[C/OL\]|[C]|g' \
        -e 's|等\.|et al.|g'
  echo '</div>'
} > "${OUT}"

echo "Wrote ${OUT}"